version: '3.8'

services:
  # Initialize Gemini authentication directory with correct permissions
  init-gemini:
    image: busybox
    volumes:
      - ~/.gemini:/host_gemini:ro
      - ./data/gemini_auth:/app/.gemini
    environment:
      - UID=${UID}
    command: >
      sh -c "
        echo 'Setting up Gemini authentication...'
        mkdir -p /app/.gemini
        if [ -d /host_gemini ]; then
          cp -r /host_gemini/* /app/.gemini/ 2>/dev/null || echo 'No files to copy'
          echo 'Gemini auth files copied successfully'
        else
          echo 'Warning: Gemini CLI not authenticated. Please run: gemini auth login'
        fi
        chown -R ${UID:-1000} /app/.gemini
        echo 'Permissions set for gemini_auth directory'
      "
    user: "0:0"
    restart: "no"

  gemini-git-ask:
    depends_on:
      - init-gemini
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: gemini-git-ask-service
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "18080:8080"
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - HOME=/app
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      # Gemini auth folder (now read-write)
      - ./data/gemini_auth:/app/.gemini
      - ./data/gemini_repositories:/app/repositories
      - ./data/gemini_logs:/app/logs
      - ./data/gemini_locks:/app/repository_locks
      - ../service/config.yaml:/app/config.yaml:ro
    networks:
      - gemini-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gemini-network:
    driver: bridge