version: '3.8'

services:
  web-demo:
    image: nginx:alpine
    container_name: github-repo-assistant-demo
    ports:
      - "18081:80"
    volumes:
      - ./demo/index.html:/usr/share/nginx/html/index.html:ro
      - ./demo/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - demo-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "traefik.enable=false"
      - "com.docker.compose.project=github-repo-assistant-demo"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  demo-network:
    driver: bridge 