version: '3.8'

services:
  gemini-git-ask:
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: gemini-git-ask-service
    restart: unless-stopped
    ports:
      - "18080:8080"
    # Use current user's UID and GID to avoid permission issues
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - NODE_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      # Alternative: Use API key instead of auth file
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      # Mount Gemini CLI authentication directory
      - ~/.gemini:/home/node/.gemini:ro
      # Mount data directories for persistence
      - gemini_repositories:/app/repositories
      - gemini_logs:/app/logs
      - gemini_locks:/app/repository_locks
      # Mount configuration file if you want to customize it
      - ../service/config.yaml:/app/config.yaml:ro
    networks:
      - gemini-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  gemini_repositories:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/repositories
  gemini_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/logs
  gemini_locks:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/locks

networks:
  gemini-network:
    driver: bridge 